### ISSUE TITLE
Does this adapter support *NIX out of the box

### ISSUE THREAD

**Issue by 3BK** [Geotab/mygeotab-api-adapter#17]
Subject says it all.

Does this adapter support any flavors of *NIX - out of the box?

**Comment by sdietz888** [comment]
The API Adapter is published for linux-x64 and _may_ work on NixOS, but no testing has been done in this regard and there are no plans to specifically support NixOS.

**Comment by 3BK** [comment]
Thanks, will check out linux-x64
________________________________
