### ISSUE TITLE
[Feature Request] More control over incoming data.

### ISSUE THREAD

**Issue by jsmorganpm** [Geotab/mygeotab-api-adapter#2]
In my specific use case, the only data I actually need is the Devices, LogRecords, and Status data.

There does not seem to be a way to turn off many of the other calls, such as Rules, Zones, or Diagnostics.

Adding a way to toggle more of the incoming feeds and caching would allow users to better control exactly what data they need.

**Comment by sdietz888** [comment]
Resolved in version 2.0 - See the change log in the guide for details.
