### ISSUE TITLE
Date Filter

### ISSUE THREAD

**Issue by isolarp** [Geotab/mygeotab-api-adapter#3]
Donde puedo ajustar desde que fecha quiero los datos?

**Comment by sdietz888** [comment]
See the [AppSettings - GeneralFeedSettings](https://docs.google.com/document/d/12TIgTCuWVF_AYc3evsIms9VOecc1NT4P9Kn-eVg-H7k/edit#heading=h.4hnib3rijddl) section in the guide for details.
