### ISSUE TITLE
Running optimizer in containers complicated by ValidateOptimizerMachineName

### ISSUE THREAD

**Issue by cdavis-67707369** [Geotab/mygeotab-api-adapter#6]
As a part of exploring using the adapter and optimizer, I've been working on running them in docker containers. Given the ephemeral nature of containers, the `OptimizerMachineName` is subject to change if we were to recreate the containers. In a mature k8s setup using deployments, it is not possible to enforce the same pod name through changes to the container's pod. 

The only workaround I can think of currently is to update/remove the rows from the `OProcessorTracking` table, but that doesn't feel great. 

Not looking for this to be solved necessarily, just wanted to bring it up as food for thought. Running the Adapter and Optimizer in containers is a must if we were going to use it in production.

**Comment by sdietz888** [comment]
This machine name validation was added to avoid situations in which users inadvertently use connection strings that point to the incorrect database, accidentally run multiple copies of the same service against a database, upgrade the application on one server and not another, etc. Those sorts of issues could cause data integrity issues with potential downstream effects. The workaround of updating the records in the OProcessorTracking table is a good solution as it would work in the scenario that you have outlined and would also require the individual(s) setting-up the process to at least be aware of what they are doing and less likely to run into these issues accidentally.

**Comment by sdietz888** [comment]
A new [DisableMachineNameValidation](https://docs.google.com/document/d/12TIgTCuWVF_AYc3evsIms9VOecc1NT4P9Kn-eVg-H7k/edit#heading=h.chlqitca3d4b) setting was added in v2.0.10 to address this issue of machine name changes in hosted environments.
