### ISSUE TITLE
Geotab Optimizer processors don't delete the data from Geotab SQL db

### ISSUE THREAD

**Issue by danicristea7511** [Geotab/mygeotab-api-adapter#7]
In the documentation of Geotab optimizer is written:
"Processor services iteratively move batches of data from tables in the adapter database to their counterpart tables in the optimizer database. **Once a batch of records has been successfully written to an optimizer database table, they are deleted from the corresponding table in the adapter database.**

I run the worker services on my local PC, but after the data are imported by the Optimizer, the Geotab SQL DB tables data are not deleted.

Could you please explain the reason?

Also, could you please give some hints whre can i fidn teh code which perform the data deletion and when it is triggered?

Thanks

**Comment by danicristea7511** [comment]
@sdietz888 Hi Steve, 

Would you please be kind and provide a feedack for the above issue. 
Thank you very much in the advance.

Daniela

**Comment by sdietz888** [comment]
Hi @danicristea7511,

Data is only deleted from tables classified as "feed data" tables (see [List of Tables](https://docs.google.com/document/d/1t8AunsFvW7NZtXaQ_9Q85qi5dR1GTfVVTYIcwXoRG1E/edit#heading=h.1gm7dxidw0tx) in the guide).

Using the LogRecordProcessor as an example, once a corresponding LogRecordT is created for the optimizer database, the subject LogRecord in the adapter database is flagged for deletion [here](https://github.com/Geotab/mygeotab-api-adapter/blob/68b74d7195bcdc6b9e162243c6c431c6e039739a/MyGeotabAPIAdapter.DataOptimizer/Services/LogRecordProcessor.cs#L177). The batch of LogRecords is then sent for deletion [here](https://github.com/Geotab/mygeotab-api-adapter/blob/68b74d7195bcdc6b9e162243c6c431c6e039739a/MyGeotabAPIAdapter.DataOptimizer/Services/LogRecordProcessor.cs#L204) as part of a Unit of Work. You can trace further from there to see more detail of the mechanics.

I hope this helps.

Steve
